USE lunchtime;

CREATE TABLE Game (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name CHAR(7) NOT NULL UNIQUE,
  created_by INT UNSIGNED NOT NULL,
  lunch_hour TINYINT UNSIGNED NOT NULL,
  lunch_minute TINYINT UNSIGNED NOT NULL,
  FOREIGN KEY (created_by) REFERENCES User (id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE GameRestaurant (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  game_id INT UNSIGNED NOT NULL,
  name VARCHAR(32) NOT NULL,
  FOREIGN KEY (game_id) REFERENCES Game (id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE GameUserMap (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  game_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (game_id) REFERENCES Game (id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES User (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT game_user_map_indx UNIQUE INDEX (game_id, user_id)
) ENGINE=INNODB;

ALTER TABLE Game ADD COLUMN started BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE Game ADD COLUMN completed BOOLEAN NOT NULL DEFAULT false;