USE lunchtime;

CREATE TABLE Game (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name CHAR(7) NOT NULL UNIQUE,
  created_by INT UNSIGNED NOT NULL,
  lunch_hour TINYINT UNSIGNED NOT NULL,
  lunch_minute TINYINT UNSIGNED NOT NULL,
  FOREIGN KEY (created_by) REFERENCES User (id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE GameRestaurant (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  game_id INT UNSIGNED NOT NULL,
  name VARCHAR(32) NOT NULL,
  FOREIGN KEY (game_id) REFERENCES Game (id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;