USE lunchtime;

CREATE TABLE GameCard (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  restaurant_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  played BOOLEAN NOT NULL DEFAULT false,
  FOREIGN KEY (restaurant_id) REFERENCES GameRestaurant (id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES User (id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

ALTER TABLE Game ADD COLUMN current_card_id INT UNSIGNED DEFAULT NULL;

ALTER TABLE Game ADD FOREIGN KEY (current_card_id) REFERENCES GameCard (id) ON UPDATE CASCADE ON DELETE CASCADE;